site_name: 42X24
site_url: https://42x24.fun/
site_author: Wyatt-Zhu
site_description: >-
  WyattZhu's blog

theme: 
  logo: images/UFO.png
  favicon: images/Mobius.svg
  name: material
  custom_dir: custom
  language: zh

  static_templates:
    - 404.html

  include_search_page: false
  search_index_only: true

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_date
  - search:
      lang: 
        - ja
        - en
  - minify:
      minify_html: true
  - glightbox

extra:
  analytics:
    provider: google
    property: G-V9C343CJV1
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Wyatt-Zhu/
      name: GitHub | Wyatt-Zhu


# # [top_right] 
# repo_name: MyBlog
# repo_url: https://github.com/Wyatt-Zhu/MyBlog/

copyright: Copyright &copy; 2022 祝宏博

nav:
  - 欢迎: "index.md"
  - 随笔:
      - 引: "随笔/index.md"
      - 文字的逻辑: "随笔/文字的逻辑.md"
  - 影评:
      - 引: "影评/index.md"
  - 搭建:
      - 测试: "搭建/index.md"
  - 学习:
      - Optical Communications: "学习/Optical Comunications/note.md"

# https://squidfunk.github.io/mkdocs-material/reference/
# https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - pymdownx.arithmatex: # support latex
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - md_in_html
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.betterem
  - pymdownx.caret # support ^
  - pymdownx.mark # support =
  - pymdownx.tilde # support ~
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true # 固定标题位置为当前位置
      title: On this page
  - pymdownx.highlight: # 代码块高亮
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.superfences: # 代码块高亮插件
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - meta # 支持Markdown文件上方自定义标题标签等

extra_css:
  - extra/css/no-footer.css 
  - extra/css/unordered-list-symbols.css # multiplt unordered list symbols
  - extra/css/color.css 

extra_javascript:
  - extra/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

